---
- name: Install Docker Packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - python-pip
    - docker

- name: Install Docker-Compose
  shell: pip install docker-Compose

- name: Upgrade Python
  shell: yum -y upgrade python-*

- service:
    name: docker
    enabled: yes
    state: started
